version: 2.1
jobs:
  build:
    parameters:
      version:
        type: string
        default: v1
      gradles:
        type: string
        default: "settings.gradle pet-clinic-service/build.gradle pet-clinic-domain/build.gradle pet-clinic-api/build.gradle buildSrc/src/main/groovy/database-conventions.gradle buildSrc/src/main/groovy/java-conventions.gradle gradle/wrapper/gradle-wrapper.properties"
    docker:
      - image: cimg/openjdk:11.0.13
    resource_class: small
    working_directory: ~/pet-clinic
    environment:
      GRADLE_OPTS: -Dorg.gradle.daemon=false
    steps:
      - checkout
      - run: cat << parameters.gradles >> > checksum.tmp.txt
      - restore_cache:
          keys:
            - << parameters.version >>-dependencies-{{ checksum "checksum.tmp.txt" }}
            - << parameters.version >>-dependencies-

      - run: ./gradlew dependencies

      - save_cache:
          paths:
            - ~/.gradle
          key: << parameters.version >>-dependencies-{{ checksum "checksum.tmp.txt" }}

      # run tests!
      - run: ./gradlew test
